import type {
  CoverVariant,
  DesignThemeKey,
  ListVariant,
  QuoteVariant,
  SectionVariant,
  TableVariant,
} from '@/types'

export interface DesignTheme {
  key: DesignThemeKey
  label: string
  eyebrow: string
  cover: CoverVariant
  section: SectionVariant
  quote: QuoteVariant
  unorderedList: ListVariant
  orderedList: ListVariant
  table: TableVariant
  endMark: string
  radius: number
  showToc: boolean
  titleOffset: number
  titleSerif: boolean
  sectionGap: number
  tocMinSections: number
}

export const designThemes: Record<DesignThemeKey, DesignTheme> = {
  qiuhe: {
    key: 'qiuhe',
    label: '秋河',
    eyebrow: '',
    cover: 'editorial',
    section: 'rule',
    quote: 'pull',
    unorderedList: 'plain',
    orderedList: 'plain',
    table: 'striped',
    endMark: '',
    radius: 4,
    showToc: false,
    titleOffset: 11,
    titleSerif: true,
    sectionGap: 36,
    tocMinSections: 3,
  },
  zhujian: {
    key: 'zhujian',
    label: '朱简',
    eyebrow: '',
    cover: 'cinnabar',
    section: 'label',
    quote: 'bar',
    unorderedList: 'plain',
    orderedList: 'plain',
    table: 'striped',
    endMark: '',
    radius: 2,
    showToc: false,
    titleOffset: 12,
    titleSerif: true,
    sectionGap: 32,
    tocMinSections: 3,
  },
  songyan: {
    key: 'songyan',
    label: '松烟',
    eyebrow: '',
    cover: 'minimal',
    section: 'numbered',
    quote: 'bar',
    unorderedList: 'ledger',
    orderedList: 'ledger',
    table: 'ledger',
    endMark: '',
    radius: 0,
    showToc: true,
    titleOffset: 10,
    titleSerif: false,
    sectionGap: 32,
    tocMinSections: 3,
  },
  yuebai: {
    key: 'yuebai',
    label: '月白',
    eyebrow: '',
    cover: 'index',
    section: 'numbered',
    quote: 'panel',
    unorderedList: 'plain',
    orderedList: 'steps',
    table: 'striped',
    endMark: '',
    radius: 6,
    showToc: true,
    titleOffset: 10,
    titleSerif: false,
    sectionGap: 32,
    tocMinSections: 3,
  },
  qingdai: {
    key: 'qingdai',
    label: '青黛',
    eyebrow: '',
    cover: 'botanical',
    section: 'marker',
    quote: 'note',
    unorderedList: 'plain',
    orderedList: 'plain',
    table: 'striped',
    endMark: '',
    radius: 6,
    showToc: false,
    titleOffset: 10,
    titleSerif: false,
    sectionGap: 36,
    tocMinSections: 3,
  },
  zhuzhi: {
    key: 'zhuzhi',
    label: '竹青纸本',
    eyebrow: '',
    cover: 'paper',
    section: 'stamp',
    quote: 'outline',
    unorderedList: 'plain',
    orderedList: 'ledger',
    table: 'striped',
    endMark: '',
    radius: 0,
    showToc: false,
    titleOffset: 10,
    titleSerif: true,
    sectionGap: 36,
    tocMinSections: 3,
  },
  haitang: {
    key: 'haitang',
    label: '海棠',
    eyebrow: '',
    cover: 'soft',
    section: 'rule',
    quote: 'pull',
    unorderedList: 'plain',
    orderedList: 'plain',
    table: 'striped',
    endMark: '',
    radius: 8,
    showToc: false,
    titleOffset: 12,
    titleSerif: true,
    sectionGap: 40,
    tocMinSections: 3,
  },
  shupian: {
    key: 'shupian',
    label: '薯片纸袋',
    eyebrow: '',
    cover: 'ticket',
    section: 'label',
    quote: 'panel',
    unorderedList: 'plain',
    orderedList: 'ledger',
    table: 'ledger',
    endMark: '',
    radius: 0,
    showToc: false,
    titleOffset: 12,
    titleSerif: false,
    sectionGap: 32,
    tocMinSections: 3,
  },
  liujin: {
    key: 'liujin',
    label: '流金',
    eyebrow: '',
    cover: 'guide',
    section: 'numbered',
    quote: 'note',
    unorderedList: 'cards',
    orderedList: 'steps',
    table: 'grid',
    endMark: '',
    radius: 6,
    showToc: true,
    titleOffset: 10,
    titleSerif: false,
    sectionGap: 32,
    tocMinSections: 3,
  },
}

export function getDesignTheme(key?: DesignThemeKey): DesignTheme {
  return designThemes[key || 'qiuhe'] || designThemes.qiuhe
}
